COLOR = "light coral"
SPEEDFACTOR = 5 #the factor that affects the speed of scale.py
RADIUS = 50 #the radius of the circle used in scale.py
SIDELEN = 70 #the side length of the triangle
SLEEPTIME = 0.05 #the time in between each frame
NUMFRAMES = 100 #the number of frames in the animation
NUMREPEATS = 4 #the number of times the animation repeats
SCREENWIDTH = 800 #the height and width of the screen
SCREENHEIGHT = 800 #the height and width of the screen
START_X = -100 # the starting xcoordinate of the drawing
START_Y = 0 # the starting ycoordinate of the drawing
